 loki-distributed:
  fullnameOverride: loki
  loki:
    config: {{ .Files.Get "config/loki.yaml" }}
  ruler:
    enabled: true
    directories:
      loki_alerts:
        rules.txt: |                                 # Sample alerting-rule using LogQL
          groups:
            - name: loki-test-group                  # rule group
              rules:
                - alert: RandomLokiTesting           # alert-name
                  expr: sum by (throughput) (rate({component="ruler"}[2m])) < 10       # LogQL expression to evaluate
                  for: 2m                            # duration for which LogQL expression should evaluate to true
                  labels:
                    severity: warning
                    team: devops
                    category: logs
                  annotations:
                    title: "Low ThroughPut Alert"
                    description: "Ruler has low throughput"
                    dashboard: "https://grafana.com/grafana/dashboards/"
                    runbook: "https://runbooks.prometheus-operator.dev"
                    logurl: "https://grafana.com/loki"
  ingester:
    persistence:
      enabled: true
      size: 1Gi
  querier:
    persistence:
      enabled: true
      size: 1Gi


promtail:
  loki:
    serviceName: "loki-gateway"
    servicePort: 3100
    serviceScheme: http
  extraScrapeConfigs:
    - job_name: journal
      journal:
        path: /var/log/journal
        max_age: 1h
        labels:
          job: systemd-journal
      relabel_configs:
        - source_labels: [ '__journal__systemd_unit' ]
          target_label: 'unit'
        - source_labels: [ '__journal__hostname' ]
          target_label: 'hostname'
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal
  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
