---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://gitlab.com/paluszkiewiczHome/argo-test.git
    targetRevision: HEAD
    path: test-project/monitoring/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://gitlab.com/paluszkiewiczHome/argo-test.git
    targetRevision: HEAD
    path: test-project/monitoring/loki
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---