apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project providing monitoring of applications installed in the cluster

  sourceRepos:
    - "https://gitlab.com/paluszkiewiczHome/argo-test.git"

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: monitoring
      server: "https://kubernetes.default.svc"

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  roles:
    # A role which provides read-only access to all applications in the project
    - name: read-only
      description: Read-only privileges to monitoring
      policies:
        - p, proj:monitoring:read-only, applications, get, monitoring/*, allow
      groups:
        - my-oidc-group

    # A role which provides sync privileges to all applications in the project, e.g. to provide sync privileges to a CI system
    - name: ci-role
      description: Sync privileges for monitoring
      policies:
        - p, proj:monitoring:ci-role, applications, sync, monitoring/*, allow