grafana:
  enabled: true
  namespaceOverride: "monitoring"
  # set pspUseAppArmor to false to fix Grafana pod Init errors
  rbac:
    pspUseAppArmor: false
  grafana.ini:
    server:
      domain: grafana.example.com
      #root_url: "%(protocol)s://%(domain)s/"
      root_url: http://grafana.example.com/
      serve_from_sub_path: true
  defaultDashboardsEnabled: true
  admin:
    existingSecret: "grafana-admin-creds"
    userKey: username
    passwordKey: password

