apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/paluszkiewiczHome/argo-test.git
    targetRevision: HEAD
    path: test-project/infra/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/paluszkiewiczHome/argo-test.git
    targetRevision: HEAD
    path: test-project/infra/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik2
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://gitlab.com/paluszkiewiczHome/argo-test.git
    targetRevision: HEAD
    path: test-project/infra/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---