apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    password: AgBYEp/iNi5nidiutiSKqPr7Okz7rYhIZuYE6dugEreyTH7Rvsu81Ni2RWUW51eTc4hWNDJm9D008mP3hBKbZEqwIshvcneFvoJh4aKPvAoaI4yleVCOS0vE10jPeAa8MH8eMXbpUbi02pfrKumQweIu56+EZte/ELyq+l2eQt/xXw6peYTzZEcLMeBkU+RjoghHAx0ft4+zAzUxj7/T3FXl8i+7z3nDrjmEau+Xdai7+3D+Ijh7PVCejC5wcGnxAAAFLVeO/KLeeqP8iI3lRCVrIEJPyHmRo8YtYxMghaa3vjYA4vzt8NnUk4bdoDEIxcD+37pWdrlPbXbqVwXFbkU+anI+0tqq2XyL/rC/CClsHFF/vk3avY4YOp6sE1nYVXjZsa0F0jwjgDnXYjtjjmyOvsdMtXu71Ac/IcNDIs+ox429kv40Wim3DXSQyXWEPnA4gfQPx+MUPREEPdO7/8AMOn/WmC/Kz8LkX25NFnfr/K3pdp80GVXlMFRonzXfIonZL2mokgILQTjBZ/kc/bGLi81mwS+g5Rw66bFJMgJzpo9lw8Ju0I2N0G192weQYq71CFILhPFpVd0vRnhqu+WEqcwPK/t17jSIzAc5uOMNqaEFv916lljH35Ddero+EYkIs60zw8v5TXfrYRwBxM2P1sy9tiv4+jh/lLorjCwYgKb0iBmD9BfgALWLzPU4ZtDqxIePB/PmLg==
    username: AgBS8uTyKc9avZs2bXd4g9vnReS679GN1E0WWQcQCzRbftTW4B70PMkmncwAh/7yUGte63iCrG5UUElPzrQcrCZicnBNIq7l2++T83GkuZIpVbXRV7cEED9abzUP5LFlBimcAKiI+7jhKqvuNzVM9Q6u5n5ZruPQVO2mnYZV56FDwoni8/TgF9BT/smNzQdJgL4RdvDRs8Gw9ZSAWplUbYgeJp2dtgf4rdXY3HH61vw6uYbcmgybZfpWxGF7lJ1WnLbL9vkPb5vMHvlylHjMakRVa99yjyojXWnCXoy0ZnVK6i3uiaMOZ7w50/cHfU1q1i5M7nsHckA/FOStSOt5TE1MF+QfTo9KB0ZGSLe+tyv+chD8vH1lMCql6IMeMdVax0oI8mPFm6HvRj7tLGBiF8S/p0iGt1U33Em+DpYywZptHkk97BDh+0NOp420ukjULv1VscLHcy2O0ctyw7Qdl4R9DYOhlN39Sw9ANhA8Qj0/VjgVooTWHLomZFCsmGS1vmDMtinssLkJG9VFGrFRPTufbsu/c/vkqHFe/3LMD/EvxtQXD/GRLkvvFPf6QfkE6Ia+Rk+KgHEQyt/hmJ6JCbf+XtqcrGBX0YPD/6Ox7znXTwJCRWMw8Btc0BANKseYoNarkrhhlclLnEIO86KdqgCuI5rSbw3uzDA7v9gT01udOPBIVmuFud5tSZnUGoCTPLds7ldVBg==
  template:
    data: null
    metadata:
      name: grafana-admin-creds
      namespace: monitoring

