apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    password: AgA42c83WlfXUyfzQuWMvBv+oTPe+wCj2ZVkNJcC5Dugj83DlHqxzIkNR2umkLY8mtT6XmzmtTDDkALjo5fZmtdwj93fk4DfcbYfPvSQiMzbXXu7udSvYWFz5YI/5rzgpLb1rYdrohnXDlZyELDEV8KFF3jOVTzw0LOYGyKJmiXfpxcWcQXDYAvwIm9G8GjZFZavk/0/9JSdzU668eeMA8BCAdyGShwDJoeWX7++rmh6zp863nPEssx+K//JxnDdxxGsnQbNI8rW7bcX5DoeC9ydjMBYQt+5KlHlZEqP1gu/Il6oIT9Wrc8w3gpQ0eCNMGRmxZn4vNCegX7ikeTE9JZFHEQAwjSC6CDibU8yLZAZG9kvKJ/jEyVY1OUYNaYjh26ZWFq0a4c1C1HrN+z4MWSMhnJMwQTTHrZCtpHsJWz6t1DP8r1rY8oAs1ociUzW+oGOVGolOR6QO0394x34XrNMB2/Nd7OzvPSUBTYDMoMh3EZaRaOya8XQMH+Uucw4qbiinLLRAiep7iuLH6YX5P9XEtxV6OOFlZPDMzpaFAir/CiRmYU95X74bYoPU3a7up0oOGIAWQQWBYHHbk0rMAXI/HtnEaTFrGLre6CCYDzK/vQLdQwFimhALAD2BPw9B7jUh3LSaAIJIfnV8Ehrn2uWrhPtlO9cevZKPery0A84CszX88SpqiOu1V9SW1FQQRwXAZhvdYdoJQ==
    username: AgB6PD363hZfpZ8DPGOT+ldpcWmRoH2PAyV6ii6rlkb6T+UVuXw/gnOQ0g2/RJPDgj1zU7x+KYWedccQKgtjkrKrw2xkMfj44asCknhhui5MDVOaXSbY2WjmGSrddwXuZa4BFMhPmXg/ofEBfdnNemfjikXZE0dQiPggoYK2z5Yw7zVspfdnYyzVATt6BgdhGLgIj2RkO18P4QRvoz4Zm2lNZwXTVrWNyRDyef5hJsHUds1dSQCkP7/CqUEzxBX/q/A0Gs8Y2UoYx1k4dcxv4JN4EUXkkbInHmUvltKVSJ1vm9UMFwL6GR2596xGCyKNHmd/HHk9NPDXK4gnrty/6X7/i3/LnOZi+8mIPbV8Cpa6sCIMXT/7MbQdAefz71hG9NtvQJb9pb6+r1rDpTAdsMPg7Vvt9Yv7BIIRcrV4B0sYGT9CSDN+zSD90nXEMqhJIIPrzuKHW8C2XsUzzORLVd1QzzGzffe4FsXCXYajoqerYSLrkfYA5AyZ8BoKL/Oj4ZppJV3f+V/zO5fD2F7fN2ttgf4Jo99t595ho3Epwuh+3+kt1BBrPLDMgGVNATR/5sLt0RQSTMqOHXYxMNwGy2kUD7YFhlg308nlOkI9NmuaFGxdTs1zkHpMX8LC0Nq+yoGtFQZi8kyIg0wFpZ05IkuHQPz+qVWYX+ez3pV6wzQiNHCgRck972SxlOH/xaDNwbHk7Le3Mg==
  template:
    data: null
    metadata:
      name: grafana-admin-creds
      namespace: monitoring

