apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    password: AgArJUo+T3lz9OJV7ARIxA8pA/QqUY18vqNmeA1dd+NdQjBF9s5u+TpziermegliJmrOvhNXDA0GdfXqZ/G+xUMd8ejeu8ES8uxbm/2+Tsv93CafwfRPk/FRlK8B0KugMqsNgZ0ySbX0Oavgj1S0GoCylVp9NODJvPomya72vAAoU3jghb0FAE9oRs9chejcfkQnuqqhLzzZuWS16s+AIQX10w13y1VdgfGF5iIE6GSPQpG6w0Y2k3NTo01ziGFLxgpH8/+xUmyUj2HFFPUjZdeaFufopZJfUNFfOj9ZzaU4jtUa3HWb2QIoDg8vNurV2skixFSa1FkufW6ttRFtPtvKpawQs9lUy2piUsyUaEOjs2br+xmDrqfRaOmFZDk0XTdg8IF/CXKX9OjD9SSbOc9WSzgpD+UNeXBKmP0u6B5Fvtq9Q/Ve7yS6fW0lvf5Pg9jWcR200xKeOUmMG9CYnrN+2PD/fV+r8x6QFNrVUodNNDvLJpxEVg1rEoQz80GTgwXrWi5mfPcBEXAXuUpBVn4uyLqqDKPDVaGS2RwDHbHG7P5+FnP94TGMkLjQcn7NNb3XgrEPt2vycFjj3LYtJPnHV4MQzBP3iP6UonRmZ66vWz6dWJj1oTIM+6YQWk9Sgx3lc45BECm1MhksnENrhO+FdnI0EzDs/xyOeWAXlSUbECfOUA/QGNkseVR5Y4We+FYHbgrMI3zPnQ==
    username: AgC+wRrISZBKfzGRg/0aeDVYmDtUQks1GcnFK2fZrKSAl5MyZt1x9yn3ioOPjDAb3lguRXdMn6CX+PIVSyjopyf0csM38k09yiDQpO5mWHf7jFVDUbpTbdYnqo6TBn7RXakUlK88dnMgCnADi9FHQVQ+UqeYusDySbc3eiA3fAtsMBTbXGk4p3edRYDwfMKFrThdASRN54FTMr6suuxZtjDYwwVhKPVuIuTIs3tfMnatDHt+WzS0KkGGj/uWrNKVai2xhFWTbjAEq8ceEByGA9l50eV423zh1V8LL9tKKbbdcmEVAJP81H/igHQS0OSJVlFzh33Vfmmi1HKfSnB6/ToETmw9f16j4lA0l+NjstG+gWoX4bcpAQEpe3ny+LTg0DR5/v29kzwujzOdL3ltDX2mehLbMoUtcRqWWDC36xS681jsdC4JzdvUfnyY1AH0Mf8FPLy5UWjYxjn2nJVmMMqLoXsWH1kop+iJvG6muJiXzxZ302yfGDNCgI5Ellz5RsFstL/u/gFoqyxlCv6gsWNxa/WEoMDEFU6F5507gSC0iwy7nI7lSroKuen+z1ezjMJnPVsBwuLLkseD7K4SCeE5MGFU4qy5sCNIs+gWB+jSGYSr+DOS6z9J/rNSrj3xyChDA0MP/84ljFz8PYzlVzUUmdPhJhLi/uYVCi9H97M0ox2p2i1Ak+ZTc3OPSWXoRrSYP5fKsQ==
  template:
    data: null
    metadata:
      name: grafana-admin-creds
      namespace: monitoring

