apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    password: AgC1ggyGhf6aphmdoCMoBbxZHwah8aFqDbGWN75+96mvsf6FT3hNIt2ynsiWd6IFvinTZRULw3nHeLaGNF/Q3dCYVbfL1dGYCx/IzhTnWYqlUzZ/uU4fEmy300cYsTg+V3Cl+d+9o3XWNOw5r7Py5wTyzioYlumCGpXTYx0mAmt0lh4vbw89X5uhglFIFOU1PEkNx6mbnyEraKOn82e93VT6DEPJvihtdoBeVds7NsUGyzQAz8CnmK0D1QUjzp93JvrfI8ybVoFSvgFxZL/wl2FifI4MRz8/4tyiY0ONv3Xdzk0xCpe1hgvwWXn8XBGVRULjeWj233MniGlzmrswGAc0ff2XV/B3EASdBoYsz5Bg6yHzZNlzuDoIUEdORpukT3slzCbzYRK0hxUlL2ik0RPtKGmViOUfHOf2QAsTafb8FnfsM3Jd88NnxTYP4/TTnGy5jX2ks84y3XG+8vje613XAcBZ8vYUBKU83Y854kNXxjOBFwHlNyV4pwJJbd7U9S52H76fPtT7UcpNqkzC979UlVaiWheVP9Ks6aZuSYVXekNNCAPwcYuzYtVUU7E2MEdLrlHdEFRUm76hW5QX7iFu2bcWSFezlc8NQCFo1httNT+Hlc8EKi7YSdZqdEc3ElRTUteQWZWP1rdkJFCXItr+MeV14mXMcYofvmalz3UttwwXRKuc4ub2mLxJA+LGtX5m/MFUCeI4fQ==
    username: AgB7M/Vvpd7z7i+O6oy3fTgh7zCTT8FdRxR+xJlIfAjMiM7VimFS+ab3zLdiut9cX6i//XaT64koBhHsjpXw9P16NsUF2oERfOmDnvuTw5bDyzxeQ5xxzsHaox+mHcvfggXCEM6wimnWKzJ8jHquQ22bOG1jDcPlQF/SPO2Q9G/qCTCjBhwIaNtUYcxR6WbW3Fe30Ai7mutw4IDTVD4GIS/piZa8kgfNyebUx7NMbspq+i1KvG+5e2F21ncUG+GBC4VotHsNdiQWRQXMlvN7vr+mqhsezerXKFky0Hwi8zlRE3zcaLtqwRkhvbww3J65tcDFKVhVTHKI+2Kr9EQiXiArgmJz7dZYSWwFXUZZAuHtOfxNy4Nxv9Jv3ZxfdDYt8Bi+u0hQdjBSHq3nFkuCDOC6oWAudlWa1itLmLqgfvrCfjEVMsSwOkMS2LTyiPuAukheNvolyE/oLWAl0+QRD+hj4YYAkEg+31akvh5BO52osCDnrupkpkHDQNYJpYZ/Fp5jhZWlGdF6ztKPpORMFlMt50lerGISrtsahzGVuaN1GQuCNKN7dTYZzNhYRpXvuBdnRDrWPxZD3YXE+ifvR1CFBjuvG3dbaS5fBkaNAWlhCDsxtcnqDb9O0c9ovnRm1jeRFU+1bdzL3exQk4bh4T7qVODfMLZxdgWyJUJfmqN33Zu3OSAplL4yuzP3fdR3WWlerGmEaQ==
  template:
    data: null
    metadata:
      name: grafana-admin-creds
      namespace: monitoring

