apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    password: AgAfd/MsLDNmh5erzyITKcD0hh11XRDu6HNYtVj5V/+1YigvzKXZG06/hXY/nJP/S1NgdPYn1rV3+AHByXdvy8InMtuESyAil0ZqxRkKl0SJ7v7CjH+CAzfGZkPg5HW+wxuQRkKMyJgqvn5rsREOorJNNbtwIY0Em6rhzx+9hUSFG5ITYa9F9/Igrj1d+J0EPYTF/xUls7wTqCXPPa/R3voBrm216X8EyUTyo5DcRmAFIV3Y0wuGbkppAlVe0rIDw+/i5R4d0T8PnV+t0mUe7RTNcpbr8iCcKc3giO3Uzz3LHlEvm/qIX1DwQ1vtiU5Xgb9RVoSjd17LPfzPY3+c+rjuGBCXS2SJrUFVcEvPzG7V1lJtkUJ/d5jPakRUMLxzCmB2TVMYL/XGZ0AXEsCIi97A2KyQ952h0gZfOcbwSaRv2LO4Zza5hHI92gusB3vOJcyk3GSiTznqxgZszpQYzQ2pb7nHLiK68jH0rluk7rWO+kbpxkC6NH6CqxU5l/CF6pOMOi9Q8OJlcouCaY4G1piPFWi2KjpoYBzNC+tTG1yML/gLGENvQWsqR50Cvb6VrhdDGmWlfZr7MKnYGKnqAaIAd+Xv1zXgJ5Tev3MdL9d8YIFl6k2NZbLfUWbLOA/yF0HeGxaMkvRUVzmsczg7GhXUmmIqQVdxCBiGwc4JHM20JxBsdX0zAJIHjqVBzuqw1rxBPKSS2Ll/qA==
    username: AgAJy8VtI5i7nvwGq2j4V1g9++FuZH32wbDDMO5/+BzB0Wie9pcPfbIdTaTQkaBH/yfS5rqBkObVzkTBzWEtZpVbGJ1SSrTGBs5qBTWkFzzICYT39Z3SaF+wShsnzrSo40e6CoGE5yQeC+SKB/jflArfR9x0IQN+jNEX9XFLcdarr4q2V4pIWU/uZgpKljHP9hg1SQr4iu+Pxqap8Jz4og/npMMDEYit45Uj7q0c4LMzsAGk255BQsoAvFaXvsevGaCEPmyXslkiBrx7hGFURs/HdmmrmEryfiOg74s8wscXjxeGj/Ix6gymzSQ3ylU2jTxVihD/xSVJz+d/uXq5KF1fX8S4lxZqqLwJRZIhbHUjqX9gi7zuHWxka5+bAtq4ifApQ0B9PwNx4Gj4O0925tKU2eAp7Tw/eSq3TuJrl++c3Cv0G3+YHBE0q7hIc7J4FQzrkLxlo6GvxdyE3ZAfHUoENPbzHGdXnaWShgxgCmdn+dAoyCeH7ZWBWJOlUL+hy2bVUKMso6g6GhTJxEmcRd0NtEIqckoU8BifvI+5uffZN1IFqv7JP/RRAnfgllZUMgy6DfWNxvyT+8652qYM+vCYWBHWcaf5mIT2G5doVxZkokJQ0vMSYMlUTabKEdozie1f4PfYAF/HL2eKo/H8vxspNMOexLiY/0tH5mqhJMIFPWgLtZNwUx5XsXB16ouwcF3yZF2m+A==
  template:
    data: null
    metadata:
      name: grafana-admin-creds
      namespace: monitoring

