apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nested-busybox3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/paluszkiewiczHome/argo-test.git
    targetRevision: HEAD
    path: test-project/application/busybox3
  destination:
    server: https://kubernetes.default.svc
    namespace: test-project
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nested-busybox4
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/paluszkiewiczHome/argo-test.git
    targetRevision: HEAD
    path: test-project/application/busybox4
  destination:
    server: https://kubernetes.default.svc
    namespace: test-project
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true