apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox4
  labels:
    app: busybox4
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: busybox4
  template:
    metadata:
      labels:
        app: busybox4
    spec:
      containers:
        - name: busybox4
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]