{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "my-private-repo-sealed",
    "namespace": "argocd",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "my-private-repo-sealed",
        "namespace": "argocd",
        "creationTimestamp": null,
        "labels": {
          "argocd.argoproj.io/secret-type": "repository"
        }
      },
      "data": null
    },
    "encryptedData": {
      "password": "AgAS3K7M6ZHC3Q6YrlwRgWtYsL4fqbT2kmQA6Rk0upXqDL5UHBE7tutEfJiQjMJlgJ/LXLeSfI7XcewGL1KjpTfvqG6acWQx0FAyj8t8DuF73DOa3IQQ1xkeSsME6iXUnYve11T+VhWB7+OyxjP+ay3LGiWwAwT7+4IDRnPjMYhJfWhFm50NhwHSTXq4z0IfWdxTISpl+HO0S7cHV5x7BBLxjtecB7eBMQDFFO537HJvYfr8gWfx5m3hFNjVFDB4S6YkHGDC3uBQDbfbpOyODd0egKGD+v7VobXzPjgvcToH2tzUBAJBJmIri7+SASZUP8BwRJysdtAaKJ4RKf7boSaJ6cGtZAe+4M6F01gt0WFKFxBrLJnly98AeTIBO9DstHcM0B+/5NXH2FtW8DQn1/+nAaYqiV19XSXc33HETNqbZu3vAevDl+0umlwA+OvhMYbXJn2mhN4n8sRo74oJARfU8UtpFWaGcPd46SRBQmYfSIs7TCTxab7E8+MoQplVnmr1TfETwBo+adYJKhdZDOrf18ehEHD1uuE/GsL0ZKw6RHTX+NuXT6vQ4XIGcmAQzsC+lNaCalZG4rWRoWnW3xhIfGv6OT7L7sIuO5HNCsAB5qqd3mocnq1q5JKw2qZUMffGi/s/vm+/t8n6grHBOMvMnIPauBbxWi12XeKAA+EWVWzfAn/siQj2VfoJpCTbi4He5x6SHWXZcwYsbTGyxHTosjBdIg==",
      "url": "AgDJgteRavCN/HGO4H1AzlHtKX1PPTexfRiO23WNqYL+h36WcYfXnZc/yqRDBMI/yFR6vwetFJr2C46vU6//XZz4MLqjgn4jS2rM07/NhFaGEBHUu6krePwDKmB0rjhNIGZ4Z6H862uSCXYAQuiaEKkT4lbsVb0NTEgFaNg50b81Z33D/eoYJZUo80Is3AFW9hrpKxbwvwYbFcEl+NqsJrQmFkfqDJL2XcgneA6FvC5bCtz0uERjUiLVVelHhoinnX5LkjIg/ts53JOgYFfMNuYKTaXyFkN6wHJzE4gRClp7w1RVV+O0x3B6l9Kgyel7D3+j0qAIcT2Xr2a4vrbDCrH5xDvS/GC94rTNrzPniq3y9ZNokcVz+n+QiS5kfEgU6Ame2dkp+u3RYVwoJXIXRZRPjFr1vRq1P+TCBiGqCfrnNJqi6Hl9lzL6SWXlqdEFRQ0jeSb8eoqN3qt2u44kfelDA4hH+LoXTZsbGQT26YACb7DIl7wQ7VjocY5v212kmw0gFgjl84Fu9NcTDODPU5eEELT9Vw7Zq5/8tgnmMAP+D/vsnv5FoOQareCoBd3Gq2c3WIyfi41kCKaEOuLD/8KGqAyiTDL1S87fOjKEnzCHsnSvKftoVM8EeQKJW0FX8vvJ5hMD+OsFfjPXYBWlFcjbUsQo5tJ8jqzC/uwY9kFTW+ZN8QtMd2DT/tijzvP8HmYYHJP5fVcClB1EhsfqX/6P/X5cgAorRbkCIvuY3uRH3BGxGFXyjtm6eqzA5fyXkCRqOA==",
      "username": "AgASZrp8CcfcSOqz47m6rCmZvhQ29g5jZnrsko3zcTCjaj/Kzjc8iB4Cc2FfepUjwF7i0Og/7PiNtuwwnMoNFDrvgQFqs0j1+bxBwM6CMpEfwdOLK8rvF28MMTVgQPi5imK1lGcB2l3dTNbgNF7QbS8wxAlcyRJikf5ZGPtg4L19T50qTzTSLXm0Z/i7BvGybn9bfavtFwc7c2jfolTqC+uwWkOb4C+6UdgqqGQkUvEkjIG3ZN0JdxBEY6VbFE/jdY40X5qbq+laanpx4UtDQWhhUQpOeSA9XqytKGmHM2dIPwX7AO2ORFjAJou8loAMI4hQKIUNZ7lSXZZunwvNxqDY28WybNzSr0aCIW3OZLKrGl/8GoieUviCuJ4EknbG7iCSFZK9FOhg9BtskkgHg/bs2iiOGpinBUbtaxazqjJqfEfGzDejrovJbsZMXFmQbAhPrXbxqIZ3afabboC2RMmt3ONYP0QRbhcTMC9yHqq8xE8oXcKpK+DuofYWMew1C8l0ghhGei6o8gMahH1BdKnp0YOvH598XwqM/W4s9hgSE3jCNitgOf/0EqDPSefZzjp6gzU4eeDdDxGGicKWnYPgoMIIF9KzwV6lYNlDXDuFU66lngmw1lu6ROWkB+aIl5EWgq87LNztGfUx30rXBsDRWspgcZijUJXcRGRHR4fmmo70dD/VYnTpoE3a5e/1DiZVUv3rmmE="
    }
  }
}
