{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "my-private-repo-sealed",
    "namespace": "argocd",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "my-private-repo-sealed",
        "namespace": "argocd",
        "creationTimestamp": null,
        "labels": {
          "argocd.argoproj.io/secret-type": "repository"
        }
      },
      "data": null
    },
    "encryptedData": {
      "password": "AgB2HM7nGhxv7EniohLaEGJw9kRSLAnJ+pG8vN+OuFWWIUXzQDAeSuiwPLR7zECdLSQBncsCH+dPWHVwovPW8GBWz9mws/jVAKIxl0u5nweUMFQ1StTjpmniEZHzUoo3+/mHaSoKwKb8DUuV7esntH/Pt8DwGm+K8vuiWFfGR+rsUJJIrFX0YQit0hDTu3l3ogfNn9sBZD+KjIWWH6GZEqDJX4OhqqQCNy7lGexZTN5YZGRd5CBJlYmTO01hL7lC5UCsHzrsCJIx/shsnLNvk6lJ8XT+G+v2CtgQNd1RNY1WHSCdXJMVfoJiLjb7B1wBQ5d0hnuEq9Cf8npZ9Tj6U0jMpWkwpkBtWgDXFPdsMd33gLsnyLjM7T632mJflyfV5+5cblfL4WZaKFGpRMggaF4TJJkzG7SFyRFj84tb+I2wBB2opu+e8eGY40yRfS1SgrmU+cJqTAV6eclcGhJGhV4Y0jmWrJXD552hIoKa1sgUxQ7Dts+pNLf6SuL/1/vxf7KBIDURdFegxIuQqd2ybTuWPjK2zPO4yG9KPwdM9PxjEIAoeB6pYT+jTZAlAaurt1nGIFQ0fIDwWn+wh2cTqKp+Iels6IkXOeuavwEhNeSTeEm/az1d/ZDrdCZEvPf1uEX9P+XGJSZiG7gdmsxmpt605XMdFJJUxaa8vIa7/ERS1iwh5bzq/XiITGeC+miULfHENVqqku7KpV+aPVbZrnKXGefLXQ==",
      "url": "AgAOnp/j3/q8jemWrrIwogy6DNOu7GnqMGnyoca1YHR4DeZM9nApL64V2LpK1NBFtPGxexjPdh3nZE3whR3BxFKf5LYfrYo9rdiVLvaUKRcRxJ7h42C8GjY9djooXt6hHIJnYAydqkMEMPJONiwnxE8c4rJwgPNDyyejnh5EP02GV/xzWB5AS541fB0SBqEgYfy9waNTrV6GgOcpyGMrqfU7JH/vRj4DPC9TTXgk44w3TYPrSNXxrwh6vM2qV6ExNftTj3yEIky3RR/HB0gfbohfe6QPA0eg5+FpDW359XVFWxUSfQQA1ycaWVMktuSU4vM53aLhGVkvNQJ+tFTKq4Vjqsa/sGQnLJdl/zqTaq36st8sRAz8wJYLtC8a1tPHaUqWQbFD0bmM+mFpXdFzAwHiep2iL2LTbmttaxkgG6Anv8/HgImUwp5JG7zHFr4SrMMfB2Ta5AFCaf+Bq9vEJTBj4owdbAemCh1arOjUtH6i9eZ/DWilsb65lkzqOB+m3h/CGqLQG8zsTMGekIUGPE+bmQyHJVyxfaR3Ey917mwLNqPDbkacqTGIvJsLBDuInLCHpvoUAx8GJMllacnsrTTs8xc7ytkLFH8ogHEaOUrYUdw4dEda0d5fmawTGfS+kNDcBpd+NbC/v/kbawx1aA0IKOQtSWrh7XaX4HBTXTphnsU1KtJOwQml3WAKj/YwYvw6yB7fDDFEGSTWN6iZ3G5gdvMp4VQow3EDWehdIjl1Z528FZ+iiXKnolUQoIhLUrJbsw==",
      "username": "AgAe479zM2N8XNonvgQ4o/wnAwIyunI5M7hNm24jDvG0TKHRGVS4o8fLZNfHjq26tJD3dhOTvPzmphuCRvvLPwwP+1torpD4+qCzer3qe1O3BrxRHu+ITIS/7kqR+CIedeALjIrjf3vTNsxtSOEFiWqWch8uWUOouqDqjfbxAnIkREj2B8mjFtnKgH2X1cwac9y2xfhRosz+4Cok98kIAdcB9qof1BMcalQczD3hCaXtmpdPF52MaAJ//65sxFzVu6o7ZzTd8h79K90AgjePX5i/ROFJ1IVxwfANqK3Ejwz8zegiUT8qgiqqxiV3TPaT+i2cS8KpIFs+mqFlj3Shpju4Uz8ydTP26fG/4VCsiLbifrcgyghxK6r6qX45XTaOnJZD9hlcyP5goedRXKkjkvQoJef9WkzmIYZaXIP2jbJelr2yTR35sDhaj864tfUeF/jRiPZRZSFql4KL19KQAJ7NXzLLb0OlG8+qwiZ/58purmu8e6sHwB+6kmBy3jKE07zjbLr6CSkUiC08QADXPt9ZmMP8EYhkTY4MQM0PlqF/Bw4y60NiK2eXe9SOVsmAScXTJpo7UCgQmbhv7iKe+oAoOoH4sgTkOdQPg7kBiQUZT3oGYWTvbiHWyH9J5Hf5bGtUvNxOMmK1YO2SJKPxCUDFGW/jvO3ut5ydUw6L6yNPJdAP+mzM893FCXt/pUNXosebIDNpaIY="
    }
  }
}
